### PR TITLE
cmd: modify the err judgment

### PR DESCRIPTION
**Pull request by q384566678**
Modify the following error situation:

```
✗ oci-runtime-tool validate 
0 errors occurred:


```

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
This is really not a good fix...., you'd better fix take advantage of multierror to fix this in CheckAll()

**Comment by q384566678** [comment]
updated, PTAL.

**Comment by Mashimiao** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
