### PR TITLE
validate: perfect deviceValid

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
adding duplicate code is not a good fix, I think the following will be better:
`case "b", "c", "u":`

**Comment by q384566678** [comment]
> adding duplicate code is not a good fix, I think the following will be better:

updated, thanks.

**Comment by Mashimiao** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
