### PR TITLE
validate_test: perfect TestJSONSchema

### PR DESCRIPTION
**Pull request by q384566678**
The test for the `DefaultAction` will be added after the spec is improved.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@liangchenye @mrunalp @Mashimiao PTAL

**Comment by Mashimiao** [comment]
LGTM

**Comment by q384566678** [comment]
ping @liangchenye

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
