### PR TITLE
release: v0.2.0

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

This release covers almost all validation items for OCI bundle, contains the following changes since v0.1.0:
894cae7 validate/validate: Linux rlimits extend the POSIX rlimits
4f756fd Specific cap-drop command
ea55f9d Specific cap-add command
5cb6c48 rootfs.tar.gz: Bump to BusyBox 1.25.1
1a9532e generate: remove redundant content
567f1aa validate: add root.path validation when platform is windows
2cbb341 validate/validate_test: Add linux.rootfsPropagation checks
6e7da81 validate/validate_test: Better error messages for unexpected JSON Schema errors
4a705c6 validate/validate_test: Handle JSON Schema test not raising an error
16be985 validate: Delete the extra validation
3935592 Godeps: Include github.com/xeipuuv/gojsonschema
6e940f8 validate: Check configuration against JSON Schema
e666f92 cap: drop existent item before validating
766302b generate: do not validate caps when being dropped
4524149 validate: Remove the wrong seccompAction valid value
26cd89b fix broken cap completion
98b055d generate: fix cap add/drop and initialize in privileged mode
0ad3376 cmd: modify the err judgment

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Sep 25, 2017 at 07:07:41AM +0000, Ma Shimiao wrote:
> … contains the following changes since v0.1.0:

I've pushed up a changelog in [1] if you want to pull that into this
release.

[1]: https://github.com/wking/ocitools-v2/tree/v0.2.0-changelog

**Comment by Mashimiao** [comment]
according to vote https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/c-eWuyhmO3Y, so far 8/11 maintainers agree this release. PTAL. Thanks.

**Comment by q384566678** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

@Mashimiao Do you want to add @wking 's changelog?

**Comment by Mashimiao** [comment]
I will add it into release not, not into commit.

**Comment by wking** [comment]
> I will add it into release not, not into commit.

I think we want an in-repo changelog [like runtime-spec][1].

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0/ChangeLog

**Comment by Mashimiao** [comment]
Adding a changelog is fine, but I have already released  this time. @wking Would you like create to a PR to add it, which may should also include changes for v0.1.0?

**Comment by wking** [comment]
On Tue, Sep 26, 2017 at 03:50:10AM +0000, Ma Shimiao wrote:
> @wking Would you like create to a PR to add it…

Done with #485.

> … which may should also include changes for v0.1.0?

I don't know if “Changes in v0.1.0” is all that useful, since nobody
will be migrating from “there wasn't a project yet” to v0.1.0.  Anyone
joining for the first time (including those whose first exposure is
v0.1.0) can just read the docs for the first version they use.
Change-logs, on the other hand, are for people who were already using
one version but who are now interested in using a different version,
and are interested in knowing what is different between the two.

**Comment by wking** [comment]
Nit: the tag should have gone on f172006, since that's what you had in
the dev@ thread.  However, you ended up putting it on the merge commit
instead:

  $ git glog --graph --oneline --decorate v0.2.0 | head -n5
  *   9d9f709 (HEAD, tag: v0.2.0, origin/master, master) Merge pull request #483 from Mashimiao/release-v0.2.0
  |\  
  | * f172006 (origin/pr/483) release: v0.2.0
  |/  
  *   0a52ac0 (wking/master) Merge pull request #460 from q384566678/devices-validate-fix

In this case it doesn't really matter, because nothing had landed in
master since f172006 branched off.  But for votes that take a bit
longer, master is likely to advance in the meantime, and those new
master commits should not be slipped into the release without being
part of the vote.  For an example of this in practice, consider
runtime-spec v1.0.0-rc6:

  runtime-spec $ git log --graph --oneline --decorate 8c0a3f4 | head -n12
  *   8c0a3f4 Merge pull request #882 from vbatts/bump-version
  |\  
  | * 0919a7d (origin/pr/882) version: master back to -dev
  | * 64d8e8e (tag: v1.0.0-rc6) version: bump version to rc6
  | * b94a1ec ChangeLog: Document changes since v1.0.0-rc5
  * |   5723c6c Merge pull request #884 from tiborvass/omitempty-typo
  |\ \  
  | |/  
  |/|   
  | * 4560f98 (origin/pr/884) Fix "omitempty" typo
  |/  
  *   f4d221c Merge pull request #880 from dqminh/wking-linux-only-capabilities-again

The typo fix from opencontainers/runtime-spec#884 should not be (and
isn't) part of v1.0.0-rc6, because it wasn't part of the voted-on
6d65997 [1,2].

The runtime-spec tag is on 64d8e8e and not 6d65997, because b94a1ec
was injected after the vote opened.  I'd rather have the maintainer
proposing the release motion already have a changelog worked up before
opening the vote, so we can use the correct hash in the motion subject
(and feel free to ping me if you want me to work up the changelog
commits), but I think sneaking in a changelog entry like that is
acceptable, where sneaking in a non-changelog change would be fairly
dubious.

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/3wLazzsd4GI
[2]: https://github.com/opencontainers/runtime-spec/commit/6d65997

**Comment by wking** [comment]
With 0.2.0 cut, I recommend we close [the v0.2.0 milestone][1].  You can do that from [the milestone list][2] by clicking “Close” for the v0.2.0 entry (see the screenshot [here][3]).

[1]: https://github.com/opencontainers/runtime-tools/milestone/4
[2]: https://github.com/opencontainers/runtime-tools/milestones
[3]: https://help.github.com/articles/viewing-your-milestone-s-progress/

**Pull request merged**
