### PR TITLE
fix some misspells

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
>Though there are two more misspells saying propogation. One in README.md, the other in man/oci-runtime-tool-generate.1.md.

I cant't find it. Can you point it out specifically?

**Comment by Mashimiao** [comment]
grep -ir 'propogation'  in the root dir of this project

**Comment by q384566678** [comment]
updated, thanks.

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
