### PR TITLE
Merge v1.0.0.rc1 into master

### PR DESCRIPTION
**Pull request by wking**
This pulls in #161, along with a bunch of other cherry-picked
backports.  New to _this_ branch (not in either v1.0.0.rc1 or master:

```
$ git log --first-parent origin/master..HEAD
commit 1ea737dc1daefb374aefcaa85c3ebff3d4e60f48
Merge: eac0762 207e26c
Author: W. Trevor King <wking@tremily.us>
Date:   Wed Aug 3 10:31:26 2016 -0700

    Merge branch 'v1.0.0.rc1'

    * v1.0.0.rc1:
      update urfave/cli package to v1.18.0
      generate: optimize namespace setup log and fix manpage
      change param type of AddProcessAdditionalGid
      remove unnecessary return error value
      Modify generate API
      Add Travis CI badge to README
      generate: fix capability.List() for cap_last_cap not exist
      generate: remove unnecessary spec initialization
      generate: fix tmpfs adding based on manpage
      Check CAP_LAST_CAP while setting privileged
      generate: Remove superfluous err check from Save

commit eac076272d2316f8257d0ed1f869bfd22500d192
Merge: b45bebd 30e2ea2
Author: W. Trevor King <wking@tremily.us>
Date:   Tue Aug 2 21:58:24 2016 -0700

    Merge commit '30e2ea2'

    With:

      $ git merge -s ours --log 30e2ea2

    because we don't want to remove the Linux pointer field adjustments
    from the backported commit.

    * commit '30e2ea2':
      Check pointer fields of g.spec

commit b45bebd09be6eeb30223b471b71f4f16d5b2a74d
Merge: 9d3881d 6acca9e
Author: W. Trevor King <wking@tremily.us>
Date:   Tue Aug 2 21:54:21 2016 -0700

    Merge commit '6acca9e'

    With:

      $ git merge -s ours --log 6acca9e

    because we don't want to roll back the master branch's runtime-spec.

    * commit '6acca9e':
      Godeps: Roll runtime-spec back to v1.0.0-rc1
```

After this series, future v1.0.0.rc1 work should be mergeable into
master without any ‘-s ours’ hoop jumping.

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Aug 03, 2016 at 10:54:27AM -0700, W. Trevor King wrote:
>     commit 1ea737dc1daefb374aefcaa85c3ebff3d4e60f48
>     Merge: eac0762 207e26c
>     Author: W. Trevor King <wking@tremily.us>
>     Date:   Wed Aug 3 10:31:26 2016 -0700
> 
>         Merge branch 'v1.0.0.rc1'
> 
>         * v1.0.0.rc1:
>           update urfave/cli package to v1.18.0
>           …
>
> After this series, future v1.0.0.rc1 work should be mergeable into
> master without any ‘-s ours’ hoop jumping.

I can update the tip commit here to pull in the current v1.0.0.rc1 tip
(which has advanced due to backported changes since I initially pushed
this PR).  But all of those backported changes are already in master,
so there should be no functional change, but the more backported
changes we merge into master, the smaller the next merge from
v1.0.0.rc1 into master will be.  Anyhow, let me know if you would like
me to update this PR or not, I'm fine either way.

**Comment by wking** [comment]
I've updated the tip commit here with 1ea737d → 4fcbcb4 to pull in the
newly-merged-into v1.0.0.rc1 #202.  So now this branch is bringing
both #202 and #161 into master (and making it easy to pull in future
v1.0.0.rc1-based changes).

**Comment by caniszczyk** [comment]
should this be closed now?

**Comment by wking** [comment]
On Tue, Nov 08, 2016 at 08:39:13AM -0800, Chris Aniszczyk wrote:
> should this be closed now?

The changes from #161 and #202 still need to be pulled into master.
If merging v1.0.0.rc1 into master is not the way maintainers want that
to happen (for example, they should close this PR with a comment to
that effect.  Maybe they'd rather me cherry-pick them into master
(like #258 did with #251)?  I still think this approach is easier long
term, but I'm not a maintainer ;).

**Comment by Mashimiao** [comment]
Rejected.  Reasons as in #258

**Comment by Mashimiao** [comment]
closed based on the result of previous discussions

**Pull request closed without merging**
