### PR TITLE
validate_test: add TestCheckMandatoryFields

### PR DESCRIPTION
**Pull request by q384566678**
Because there are so many cases, I only chose part of the test.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@liangchenye PTAL

**Comment by q384566678** [comment]
@liangchenye PTAL

**Comment by liangchenye** [comment]
Looking into this.
I'm checking if the unit test cover all cases of this function.

**Comment by liangchenye** [comment]
It looks good. I just found the original function does not handle one case -- the 'v.spec == nil'.
Can you fix it and add the related unit test?

**Comment by q384566678** [comment]
updated, thanks. PTAL.

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
