### PR TITLE
[1.0.0.rc1] man: add tty option and tfix

### PR DESCRIPTION
**Pull request by wking**
Backporting #154 to v1.0.0.rc1 following [the first procedure here](https://github.com/opencontainers/ocitools/pull/140#issuecomment-234626841).

### CODE REVIEW

**Comment by mrunalp** [comment]
I see 5 commits including 4 merge commits. Is that intentional?

**Comment by wking** [comment]
On Thu, Jul 28, 2016 at 04:04:28PM -0700, Mrunal Patel wrote:
> I see 5 commits including 4 merge commits. Is that intentional?

562e912 was behind #140 landing:

  $ git log --graph --oneline --decorate f0ecc98 | head -n6
  *   f0ecc98 Merge pull request #140 from hmeng-19/update_vendor
  |\  
  | * 6e7b418 (origin/pr/140) Update runtime-spec package
  * |   564b30e Merge pull request #147 from Mashimiao/move-default-cap-to-validate
  |\ \  
  | * | 5f07d9d (origin/pr/151, origin/pr/147) move defaultCaps to validate

so I just PRed it directly without cherry-picking.  The only thing we
don't want in v1.0.0.rc1 is 6e7b418 and stuff that needs those Linux
pointers.

**Comment by wking** [comment]
On Thu, Jul 28, 2016 at 04:15:30PM -0700, W. Trevor King wrote:
> 562e912 was behind #140 landing:
> 
>   $ git log --graph --oneline --decorate f0ecc98 | head -n6

And that would be easier to see if the graph actually included 562e912
:p.  Here's a better view:

  $ git log --graph --oneline --decorate f0ecc98 562e912 | head -n6
  * 562e912 (wking/man-add-tty-and-tfix, origin/pr/162, origin/pr/154, man-add-tty-and-tfix) man: add tty option and tfix
  | *   f0ecc98 Merge pull request #140 from hmeng-19/update_vendor
  | |\  
  |/ /  
  | * 6e7b418 (origin/pr/140) Update runtime-spec package
  * |   564b30e Merge pull request #147 from Mashimiao/move-default-cap-to-validate

So 562e912 is based on the last master commit before #140 landed.

**Comment by wking** [comment]
Anything I can to do help move this along?  GitHub says there are
conflicts, but this applies cleanly if I merge locally:

  $ git checkout v1.0.0.rc1
  Switched to branch 'v1.0.0.rc1'
  Your branch is up-to-date with 'origin/v1.0.0.rc1'.
  $ git merge man-add-tty-and-tfix
  Auto-merging man/oci-runtime-tool-generate.1.md
  Auto-merging cmd/oci-runtime-tool/generate.go
  Merge made by the 'recursive' strategy.
   cmd/oci-runtime-tool/generate.go   | 6 +++---
   man/oci-runtime-tool-generate.1.md | 5 ++++-
   2 files changed, 7 insertions(+), 4 deletions(-)

**Comment by Mashimiao** [comment]
I think your branch man-add-tty-and-tfix may checkout from wrong branch. you may need create a new man-add-tty-and-tfix branch again and push PR again.

**Comment by wking** [comment]
On Wed, Sep 28, 2016 at 01:22:13AM -0700, Ma Shimiao wrote:
> I think your branch man-add-tty-and-tfix may checkout from wrong
> branch. you may need create a new man-add-tty-and-tfix branch again
> and push PR again.

562e912 (originally submitted as #154) branched off of master *before*
the 1.0.0.rc1-breaking runtime-spec bump [1].  So this is good to
merge into v1.0.0.rc1 without any need to cherry-pick anything.  And
avoiding unnecessary cherry picks makes life easier on Git if/when we
eventually merge v1.0.0.rc1 into master to pickup the v1.0.0.rc1-only
commits (#181).

[1]: https://github.com/opencontainers/runtime-tools/pull/162#issuecomment-236055889

**Comment by Mashimiao** [comment]
anyway, 4 merge commits is not expected. Maybe reset would make any sense?

**Comment by wking** [comment]
On Thu, Sep 29, 2016 at 01:48:08AM -0700, Ma Shimiao wrote:
> anyway, 4 merge commits is not expected.

Am I just explaining it poorly?  Or does the explanation make sense
and you just prefer a cherry-picks for a simpler v1.0.0.rc1 history?
If we go with the cherry-picks here, do you want more cherry picks
instead of a merge in #181?

I think this would be a lot less work if we just focused new PRs on a
branch pinned to a specific runtime-spec release instead of putting
most development work into a branch that floats with runtime-spec's
master.  But I pitched that in #140 and don't seem to have made a
convincing-enough argument ;).

**Pull request closed without merging**
