### PR TITLE
generate: solve conflicting options problem

### PR DESCRIPTION
**Pull request by Mashimiao**
In my option, there is not any other good ways to solve conflicting
options problem except adding note for warning.

Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
SGTM, `process-cap-drop-all` should also be modified.

**Comment by Mashimiao** [comment]
updated, thanks

**Comment by q384566678** [comment]
LGTM

**Comment by q384566678** [comment]
LGTM

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
