### PR TITLE
Hooks should be passed in as rspec.Hook, not as a string.

### PR DESCRIPTION
**Pull request by rhatdan**
The marshalling should not be required to be used inside of the interface.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by mrunalp** [comment]
LGTM

**Comment by rhatdan** [comment]
@vbatts @vishh @philips @crosbymichael @dqminh @caniszczyk PTAL

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
