### PR TITLE
update runtime-spec v1.1.0

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on https://github.com/opencontainers/runtime-tools/pull/773

Update some dependencies to released versions;

### go.mod: github.com/opencontainers/runtime-spec v1.1.0

full diff: https://github.com/opencontainers/runtime-spec/compare/86290f6a00fb...v1.1.0

### CODE REVIEW

**Comment by thaJeztah** [comment]
@kolyshkin @mrunalp ptal 🤗

**Comment by cyphar** [comment]
Can we do a release without this change, and then another release with this change? The lack of a release with `go.mod` means that you cannot use `go install` to get a `1.0.2`-compatible runtime-tool validator (0.9 doesn't have a go.mod so you pull the 1.1.0 spec which causes `runtime-tools` to think that it is a `1.1.0` spec validator). This is currently breaking umoci's CI, and will be an issue for historical users that need the older spec version.

**Comment by cyphar** [comment]
Or, we can put the `golang.org/x/sys` update into a separate PR.

**Comment by cyphar** [comment]
We could fork from 0.9 and release a 0.9.1 that "just" does the go.mod migration and upgrades to 1.0.2 (with cherry-picking if absolutely necessary(. That way, we won't have to worry about reverting things from `main` and `0.10.0` could be a strict upgrade.

That being said, given that 0.9 was also a release that had a non-released spec version I think it's not too crazy to just say that 0.10 can similarly just be a fruity intermediate runtime-spec version in keeping with all of the other releases of runtime-tools, and we will stop doing that in future releases.

**Comment by cyphar** [comment]
Based on looking at the git logs, there was actually only one patch "needed" for us to support v1.0.2, so that approach seemed much simpler. See #774.

**Review by cyphar — APPROVED** [review]
On reflection, just doing this is a better idea.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
