### PR TITLE
Add commit to version info

### PR DESCRIPTION
**Pull request by q384566678**
It make user know more information about `oci-runtime-tool`.

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
In my opinion, users don't need to know commit info. But not strongly oppose

**Comment by liangchenye** [comment]
Need rebase, but +1 for this.

**Comment by q384566678** [comment]
updated.

**Comment by liangchenye** [comment]
LGTM

**Comment by Mashimiao** [comment]
LGTM

**Pull request merged**
