### PR TITLE
adding security and CoC links

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

This will add a link to the code of conduct and security pages to address https://github.com/opencontainers/org/issues/3

### CODE REVIEW

**Comment by vsoch** [comment]
Don't merge - I need to update link!

**Comment by vsoch** [comment]
ok links should be good!

**Comment by mrunalp** [comment]
LGTM

**Comment by vsoch** [comment]
Gotta be consistent!

**Pull request merged**
