### PR TITLE
Add apparmor profile test

### PR DESCRIPTION
**Pull request by q384566678**
Add apparmorProfile validation in runtimetest and validation.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@liangchenye PTAL.

**Comment by q384566678** [comment]
ping @liangchenye

**Comment by q384566678** [comment]
After this merge, we basically completed all the runtime validation.

**Comment by q384566678** [comment]
@mrunalp @liangchenye PTAL

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
