### PR TITLE
generate/seccomp: Allow Landlock syscalls

### PR DESCRIPTION
**Pull request by l0kod**
Landlock is a Linux feature that enables creating security sandboxes
(see https://docs.kernel.org/userspace-api/landlock.html).  Allow the
three related system calls (available since Linux 5.13):
landlock_create_ruleset, landlock_add_rule, and
landlock_restrict_self.

Signed-off-by: Mickaël Salaün <mic@digikod.net>

### CODE REVIEW

**Comment by l0kod** [comment]
This is equivalent to https://github.com/containers/common/pull/1081 and https://github.com/moby/moby/pull/43199

**Comment by rhatdan** [comment]
@giuseppe @vbatts @mrunalp @AkihiroSuda @kolyshkin PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
close/reopen to kick ci

**Pull request merged**
