### PR TITLE
generator solaris application container configuration

### PR DESCRIPTION
**Pull request by q384566678**
Add some options to generate solaris application container configuration

Signed-off-by: Zhou Hao zhouhao@cn.fujitsu.com

### CODE REVIEW

**Comment by Mashimiao** [comment]
LGTM

**Comment by q384566678** [comment]
@liangchenye Do you think that's ok? If this and #528  can be merged, we have perfected all the generate functions.

**Comment by q384566678** [comment]
@liangchenye @mrunalp PTAL

**Comment by liangchenye** [comment]
LGTM

**Comment by Mashimiao** [comment]
LGTM

**Pull request merged**
