### PR TITLE
runtimetest: fix nil dereference

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
In logic, this is a correct fix. But in fact, this is impossible, because if process is nil, the container can not be run.

**Comment by wking** [comment]
On Thu, Nov 23, 2017 at 07:07:31AM +0000, Ma Shimiao wrote:
> In logic, this is a correct fix. But in fact, this is impossible,
> because if process is nil, the container can not be run.

I sometimes call runtimetest in my host environment (i.e. without a
wrapping runtime invocation).  This guard will help in that case,
although I'm also fine with panics there, since that's not how
runtimetest is intended to be used.  So I have no opinion on this PR,
but maintainers might want to consider that use case when deciding on
it.

**Comment by Mashimiao** [comment]
LGTM

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
