### PR TITLE
completions: cleanup and fix

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by Mashimiao** [comment]
rebased. @mrunalp  @liangchenye  @hqhq  PTAL

**Comment by hqhq** [comment]
LGTM

**Comment by Mashimiao** [comment]
@mrunalp  @liangchenye  PTAL

**Comment by Mashimiao** [comment]
@mrunalp  @hqhq  CI failed to get status, I updated PR. Can you re-LGTM?

**Comment by hqhq** [comment]
LGTM

**Comment by Mashimiao** [comment]
@liangchenye  @mrunalp  PTAL

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
