### PR TITLE
travis: update go versions

### PR DESCRIPTION
**Pull request by dvrkps**
Signed-off-by: Davor Kapsa <davor.kapsa@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
[PullApprove is still not happy][1], because [your Signed-off-by email does not match your author][2].

```
$ git show origin/pr/487 | head -n7
commit e4f37c26dc089b5914aba6112bc241e8341de5cb
Author: Davor Kapsa <dvrkps@users.noreply.github.com>
Date:   Wed Sep 27 12:38:47 2017 +0200

    travis: update go versions
    
    Signed-off-by: Davor Kapsa <davor.kapsa@gmail.com>
```

I [still][1] think the easiest fix would be to allow edits from maintainers for this PR, and then they can fix it for you ;).

[1]: https://pullapprove.com/opencontainers/runtime-tools/pull-request/487/requirements/
[2]: https://github.com/opencontainers/runtime-tools/pull/482#issuecomment-331543587

**Comment by dvrkps** [comment]
@wking I check "Allow edits from maintainers."

**Comment by Mashimiao** [comment]
I think we can't edit the commit's author

**Comment by dvrkps** [comment]
@Mashimiao @wking I set my email address to public.
Can anybody trigger sign-off-by check again?

**Comment by wking** [comment]
> I think we can't edit the commit's author

Bummer.  It sounded like you could [force-push to `patch-2` in https://github.com/dvrkps/runtime-tools.git`][1], after a local `git commit --amend --author '...' --no-edit`.

[1]: https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by Mashimiao** [comment]
@wking  Oh, I haven't used such funciton. @dvrkps  re-edit your author's email, I think problem has been solved.

**Comment by dvrkps** [comment]
@Mashimiao re-edit as back to hiden email address ?

**Comment by Mashimiao** [comment]
I modified the author's email of this commit to be the same as signed-off-by, davor.kapsa@gmail.com

**Comment by wking** [comment]
On Thu, Sep 28, 2017 at 10:35:36PM -0700, Davor Kapsa wrote:
> @Mashimiao re-edit as back to hiden email address ?

PullApprove is happy [1], so you don't need to touch anything :).

[1]: https://pullapprove.com/opencontainers/runtime-tools/pull-request/487/requirements/

**Comment by Mashimiao** [comment]
LGTM

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
