### PR TITLE
release v0.8.0

### PR DESCRIPTION
**Pull request by q384566678**
According to the plan in [ROADMAP,](https://github.com/opencontainers/runtime-tools/issues/465) we have implemented the verification of the remaining specerror, so we are ready to release version 0.8 as planned.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
The version of the vote was launched yesterday, we can put this pr in the next version, because there are many similar work to be done.

**Comment by jterry75** [comment]
No problem. Thanks for taking a look

**Comment by q384566678** [comment]
The vote on this new version has been passed. Here's the link:
https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/fcJGtzJrf7Q

@hqhq @vbatts PTAL.

**Comment by q384566678** [comment]
@crosbymichael @vbatts @mrunalp @liangchenye @hqhq @vishh @dqminh @tianon PTAL

**Comment by hqhq** [comment]
LGTM

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
