### PR TITLE
gof(ump)t code

### PR DESCRIPTION
**Pull request by thaJeztah**
format the code with gofumpt (which is a superset of gofmt)

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@giuseppe @mrunalp PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@AkihiroSuda @kolyshkin @mrunalp PTAL

**Review by cyphar — APPROVED** [review]
lgtm

**Pull request merged**
