### PR TITLE
sort options list by letter

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

After this, users can be more easier to find options

### CODE REVIEW

**Comment by wking** [comment]
cbc3dac0 looks good to me.

**Comment by initlove** [comment]
LGTM

(and so the later PR should also care about this)

**Comment by Mashimiao** [comment]
PR updated. 
Ping @mrunalp  @liangchenye

**Comment by liangchenye** [comment]
+1 for this.

**Comment by mrunalp** [comment]
Looks good but needs rebase.

**Comment by Mashimiao** [comment]
@mrunalp  rebased

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
