### PR TITLE
Modify the legal value of the rootfs-propagation

### PR DESCRIPTION
**Pull request by q384566678**
This is a supplement to the #543.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by wking** [comment]
[The Travis failure][1] looks like a network hiccup.

[1]: https://travis-ci.org/opencontainers/runtime-tools/jobs/325711882#L489

**Comment by q384566678** [comment]
@liangchenye PTAL

**Comment by q384566678** [comment]
ping @liangchenye

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
