### PR TITLE
platform config could exist even platform is different

### PR DESCRIPTION
**Pull request by liangchenye**
Signed-off-by: liangchenye <liangchenye@huawei.com>

### CODE REVIEW

**Comment by liangchenye** [comment]
The spec is changed from
```
linux (object, optional) Linux-specific configuration. This SHOULD only be set if platform.os is linux.
solaris (object, optional) Solaris-specific configuration. This SHOULD only be set if platform.os is solaris.
```
to 
```
linux (object, OPTIONAL) Linux-specific configuration. This MAY be set if the target platform of this spec is linux.
windows (object, OPTIONAL) Windows-specific configuration. This MUST be set if the target platform of this spec is windows.
solaris (object, OPTIONAL) Solaris-specific configuration. This MAY be set if the target platform of this spec is solaris.
```

So I added this PR.  @q384566678 @Mashimiao 
I notice this when I worked on #66 .

**Comment by Mashimiao** [comment]
LGTM

**Comment by Mashimiao** [comment]
LGTM

**Comment by Mashimiao** [comment]
ping @hqhq  @mrunalp

**Comment by mrunalp** [comment]
LGTM

**Comment by Mashimiao** [comment]
LGTM

**Pull request merged**
