### PR TITLE
automatically get os when validating runtime

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by liangchenye** [comment]
:+1: 

The man page should be cleaned as well.

**Comment by Mashimiao** [comment]
which manpage?  runtimetest seems doesn't have any mange.

**Comment by liangchenye** [comment]
Sorry, wrong comment, I mess the man page up.

**Comment by liangchenye** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
