### PR TITLE
add pullapprove.yml as PullApprove enabled

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by wking** [comment]
076e5dcf looks good to me (except for the team, it matches the
in-flight opencontainers/project-template#21).

I'd rather be addressing this sort of thing by landing the
project-template PRs (possibly after OCI-wide maintainer votes) and
then merging project-template's master into this repository.  But if
updating project-template is too difficult, cherry-picks like this to
pull content over a piece at a time will work.

**Comment by hqhq** [comment]
LGTM

**Comment by wking** [comment]
I don't know if branch-protection is setup for this repo, but if it is
we may need @caniszczyk to approve it [1].

[1]: https://pullapprove.com/opencontainers/runtime-tools/pull-request/261/

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
@cra pullapprove is asking for your review for this to be merged. Not sure why.

**Comment by mrunalp** [comment]
@caniszczyk PTAL

**Comment by caniszczyk** [comment]
LGTM

**Pull request merged**
