### PR TITLE
cmd/runtimetest: Add an app description

### PR DESCRIPTION
**Pull request by wking**
Cherry-picking #260 onto master.

### CODE REVIEW

**Comment by liangchenye** [comment]
LGTM

**Comment by Mashimiao** [comment]
I think there is no need to add test files in urfave/cli.

**Comment by wking** [comment]
On Tue, Nov 22, 2016 at 05:50:45PM -0800, Ma Shimiao wrote:
> I think there is no need to add test files in urfave/cli.

I'm just running ‘godep update github.com/urfave/cli’ (as quoted in
the commit message).  If I should be doing something else instead,
just tell me what to paste in ;).

**Comment by Mashimiao** [comment]
I also tried to update urfave/cli and no test files were added. Maybe you need to update you godep version

**Comment by wking** [comment]
On Tue, Nov 22, 2016 at 11:18:42PM -0800, Ma Shimiao wrote:
> Maybe you need to update you godep version

That was the problem, thanks :).  urfave/cli tests dropped with
afbe433 → 4057aaf.

With godep v75 the update printed two warnings:

  godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.
  godep: WARNING: Go version (go1.7) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists

I'm not familiar enough with Godep to know what (if anything) we're
supposed to do to migrate to whatever the new approaches are.

**Comment by Mashimiao** [comment]
About godeps and workspace changes, I have create RP #231 to solve this problem.
In my opinion, all problems of godep we can solve in #231 
But if you want to update urfave/cli in this PR, I also don't think this is a problem.

**Comment by Mashimiao** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
