### PR TITLE
runtimetest: split linux specified part of process validation

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by wking** [comment]
222489f6 looks good to me.  Do you have another platform's process validation in mind, or are you preparing for the more distant future?

**Comment by Mashimiao** [comment]
Yes, but first perfect Linux-based validation

**Comment by mrunalp** [comment]
LGTM

**Comment by Mashimiao** [comment]
Yes, but first perfect Linux-based validation

**Pull request merged**
