### PR TITLE
generate: add support for domainname

### PR DESCRIPTION
**Pull request by cdoern**
runtime-spec recently added support for a Domainname entity, add handling for it here to be used by runtimes.

Signed-off-by: Charlie Doern <cdoern@redhat.com>

### CODE REVIEW

**Comment by cdoern** [comment]
@kolyshkin @mrunalp PTAL

**Comment by cdoern** [comment]
cc @giuseppe

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by cdoern** [comment]
ping @kolyshkin @mrunalp

**Comment by cdoern** [comment]
@mrunalp @dfr @kolyshkin PTAL, this needs to get in for podman to use it.

**Comment by dfr** [comment]
LGTM but I'm not a maintainer here.

**Review by mrunalp — APPROVED** [review]
LGTM

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
close/reopen to kick ci

**Pull request merged**
