### PR TITLE
generate: windows-specific container configuration generate

### PR DESCRIPTION
**Pull request by q384566678**
Add some options to generate windows-specific container configuration.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
LGTM

**Comment by liangchenye** [comment]
LGTM

**Comment by Mashimiao** [comment]
LGTM

**Comment by Mashimiao** [comment]
please solve conflicts

**Comment by q384566678** [comment]
@liangchenye @Mashimiao rebased, PTAL

**Comment by q384566678** [comment]
@liangchenye @Mashimiao PTAL

**Comment by Mashimiao** [comment]
LGTM

**Comment by q384566678** [comment]
ping @liangchenye

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
