### PR TITLE
add runtime-spec initial maintainers

### PR DESCRIPTION
**Pull request by liangchenye**
#238 #237
Signed-off-by: liang chenye <liangchenye@huawei.com>

### CODE REVIEW

**Comment by liangchenye** [comment]
PTAL @mrunalp @Mashimiao @wking @caniszczyk

**Comment by wking** [comment]
How I expected this to work in the wake of opencontainers/tob#18 was:

1. One PR to update the local MAINTAINERS file to match runtime-spec.
   This doesn't need any local LGTMs because it has already been voted
   on by the TOB [1].

2. A follow-up PR or two to add @liangchenye and @Mashimiao.  These
   need ⅔ votes of whoever happens to be in MAINTAINERS at the time,
   with a “five business days” period [2].  Although I don't think
   that five-day limit is particularly serious, and was certainly not
   met by opencontainers/runc#503 which was open for almost three
   months.

Can we make this PR just about (1)?

[1]: https://groups.google.com/a/opencontainers.org/d/msg/tob/rZ4luMa-pxY/SX2mpI1MBQAJ
     Subject: Re: [oci-tob] Re: VOTE Required: approve new projects: image-tools, runtime-tools
     Date: Wed, 14 Sep 2016 17:48:33 +0000
     Message-ID: <CAD2oYtO_4Ghf5hJ04fDXHqCF8-oyDEQ_8wKC5Rcgcbh+M0kBrw@mail.gmail.com>
[2]: https://github.com/opencontainers/runtime-tools/blob/fa7a8635539f3a5e264ce2e14d2f9e5d43af9334/MAINTAINERS_GUIDE.md#how-are-maintainers-added

**Comment by liangchenye** [comment]
@wking  Changed

**Comment by wking** [comment]
fdc08b0df9 looks like what the TOB voted in to me:

  $ sha1sum ../runtime-spec/MAINTAINERS <(git cat-file -p origin/pr/239:MAINTAINERS)
  8269472b2299d8dadd499a0c15193189dabc4400  ../runtime-spec/MAINTAINERS
  8269472b2299d8dadd499a0c15193189dabc4400  /dev/fd/63

**Comment by mrunalp** [comment]
LGTM

**Comment by wking** [comment]
On Thu, Oct 13, 2016 at 12:07:44PM -0700, Mrunal Patel wrote:
> Merged #239.

The runtime-tools-maintainers group should be updated to reflect this
change so folks don't have to use runtime-spec-maintainers [1].

[1]: https://github.com/opencontainers/runtime-tools/pull/249#issuecomment-253836910

**Pull request merged**
