### PR TITLE
generate: add --linux-device-cgroup-add and --linux-device-cgroup-remove

### PR DESCRIPTION
**Pull request by q384566678**
These options allow user to configures the device whitelist.

Usage:
```
oci-runtime-tool generate \
--linux-device-cgroup-remove=deny,access=rwm \
--linux-device-cgroup-add=allow,type=c,major=10,minor=229,access=rw \
-linux-device-cgroup-add=allow,type=b,major=8,minor=0,access=r
```

Closes #314 

This is a rebase of #314 

Signed-off-by: Zhai Zhaoxuan <zhaizx.fnst@cn.fujitsu.com>
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@opencontainers/runtime-tools-maintainers PTAL

**Comment by Mashimiao** [comment]
LGTM

**Comment by q384566678** [comment]
ping @liangchenye

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
