### PR TITLE
MAINTAINERS: add Zhou Hao

### PR DESCRIPTION
**Pull request by Mashimiao**
Hello, @opencontainers/runtime-tools-maintainers 

Though we have done a lot of work, but we still have so many PRs are pending for a long time.
I think we may need more maintainers to work hard together.
Zhou Hao(zhaohao@cn.fujitsu.com) has done quite a bit of work so far!

https://github.com/opencontainers/runtime-tools/commits?author=q384566678

And he is also one of the image-tools maintainers, I believe he has enough experience and ability to manage runtime-tools.
If you agree, please reply LGTM

Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by hqhq** [comment]
LGTM

**Comment by liangchenye** [comment]
LGTM

**Comment by Mashimiao** [comment]
ping @crosbymichael  @vbatts  @vishh @mrunalp  @dqminh  @philips  @tianon

**Comment by vbatts** [comment]
LGTM
(also, this is likely best sent to the dev@ mailing list as well)

**Comment by mrunalp** [comment]
LGTM

**Comment by wking** [comment]
On Wed, Jul 26, 2017 at 02:53:54AM +0000, Vincent Batts wrote:
> (also, this is likely best sent to the dev@ mailing list as well)

Past runtime-tools maintainer changes have been GitHub only (#249,
#337), and there's nothing about dev@ in [1].  You may be thinking
about GOVERNANCE.md (which hasn't landed in runtime-tools, with the
only attempt to include it being rejected in #274).  And even with
project-template's GOVERNANCE.md, maintainer addition is not clearly
attached to the GOVERNANCE.md votes without the in-flight [2].  So
until at least some of that happens, I think GitHub-only runtime-tools
votes are fine.

[1]: https://github.com/opencontainers/runtime-tools/blob/2d270b8764c02228eeb13e36f076f5ce6f2e3591/MAINTAINERS_GUIDE.md#how-are-maintainers-added
[2]: https://github.com/opencontainers/project-template/pull/20/files#diff-cc177b5b54bfdc5f9e1697d2c1ec1dc0R87

**Comment by tianon** [comment]
LGTM

**Comment by vishh** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Comment by caniszczyk** [comment]
8/10 maintainers approve which is good enough for the 2/3's margin required.

Thank you @Mashimiao for kicking this off and sorry for the delay!

**Comment by caniszczyk** [comment]
Also @Mashimiao, can you send a welcome email to the dev@opencontainers.org announcing the new maintainer for the runtime-tools project? Thank you!

**Comment by Mashimiao** [comment]
@caniszczyk  of course I can, I will send later.

**Pull request merged**
