### PR TITLE
Report all errors

### PR DESCRIPTION
**Pull request by mrunalp**
This makes runtime validation report all errors at the end.

### CODE REVIEW

**Comment by mrunalp** [comment]
@Mashimiao @wking @hqhq @liangchenye PTAL

**Comment by wking** [comment]
Producing TAP output (e.g. with [1]) gives you output that you can
feed into a number of TAP consumers [2].  Since runtimetest isn't a
library, there's no need for errors that are conveniently handled in
Go, so I'd prefer TAP output.

But 8e366c8 is a reasonably small change (which retooling the existing
checks to output TAP would be a bit more work), so I'm ok with it.
Either way (go-multierror or TAP) would be better than the quick death
we have now.

[1]: https://github.com/mndrix/tap-go
[2]: https://testanything.org/consumers.html

**Comment by Mashimiao** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
