### PR TITLE
Bump version to 0.0.2

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Mar 02, 2017 at 01:45:15PM -0800, Daniel J Walsh wrote:
>   * Bump version to 0.0.2

We haven't actually tagged a release yet.  Is there a purpose to
bumping the runtime-tools version without cutting releases?

**Comment by rhatdan** [comment]
I am fine with what ever procedure we can to update the release number.  The bottom line is this package is in Fedora with a very old version, I want to get it updated.

**Comment by wking** [comment]
On Thu, Mar 02, 2017 at 02:43:26PM -0800, Daniel J Walsh wrote:
> The bottom line is this package is in Fedora with a very old
> version, I want to get it updated.

To me that sounds like “we need to start cutting runtime-tools
releases”, and I think that would be a great idea.

**Comment by rhatdan** [comment]
:+1:

**Comment by mrunalp** [comment]
Let's update with the runtime-spec rc5 and then get 1.0 rc for runtime-tools.

**Comment by wking** [comment]
On Tue, Mar 07, 2017 at 11:42:28AM -0800, Mrunal Patel wrote:
> Let's update with the runtime-spec rc5 and then get 1.0 rc for
> runtime-tools.

Before we jump straight to a 1.0 RC, I think we should land #321.  I
think that is only blocked on “where runtime-tools maintainers want
the JSON Schema from the runtime-spec PR” (link to that JSON Schema in
[1]).  Until we document the API we're testing (and ideally, update
our implementation to use that API, e.g. splitting create/start in
[2]), I recommend sticking with more modest release numbers like
0.1.0, 0.2.0, etc.  Hopefully that will avoid the ¾-year period in 1.0
“RCs” which runtime-spec has gone through.

[1]: https://github.com/opencontainers/runtime-tools/pull/321#issue-206681629
[2]: https://github.com/opencontainers/runtime-tools/blob/8392e59c7c11b146462e20701c912242f83cf110/cmd/oci-runtime-tool/runtime_validate.go#L74

**Pull request closed without merging**
