### PR TITLE
generate: enhance options parse

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
ping @liangchenye  @mrunalp  @hqhq

**Comment by liangchenye** [comment]
LGTM

**Comment by Mashimiao** [comment]
@hqhq  @mrunalp  PTAL

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
