### PR TITLE
Vendor in windows runtime-spec changes

### PR DESCRIPTION
**Pull request by madhanrm**
Signed-off-by: Madhan Raj Mookkandy <madhanm@microsoft.com>

### CODE REVIEW

**Comment by madhanrm** [comment]
A Follow up PR to use the vendor'd-in windows namespace changes is on the way.

**Comment by madhanrm** [comment]
@crosbymichael Can you approve this vendor PR?

**Comment by madhanrm** [comment]
FYI @dineshgovindasamy

**Comment by madhanrm** [comment]
ping @crosbymichael, @vishh,  @mrunalp @vbatts @dqminh @philips  @tianon  @hqhq @liangchenye  @Mashimiao @q384566678

**Comment by vbatts** [comment]
LGTM

**Comment by madhanrm** [comment]
Can some get this merged? I have to vendor this change in other repros. Thanks !

**Pull request merged**
