### PR TITLE
Set pids limit when set through the CLI

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
e9cebd7da looks good to me.

And we might want to take another look at #159 and see if it dropped
anything else like this [1] accidentally.

[1]: https://github.com/opencontainers/runtime-tools/pull/159/files#diff-6f4f1d634b27b29e44d7362bbaf936d8L398

**Comment by Mashimiao** [comment]
LGTM

**Comment by Mashimiao** [comment]
LGTM

**Comment by mrunalp** [comment]
@liangchenye PTAL

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
