### PR TITLE
Relax LGTM requirement

### PR DESCRIPTION
**Pull request by caniszczyk**
There has been a request to relax the number of LGTMs in the tools projects to help improve merge rate.

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
Should this also come with a `MAINTAINERS` prune?  I'm surprised that a project with 11 active maintainers would have difficulty collecting two LGTMs, so if we are having trouble with that, then all 11 maintainers are probably not active.

**Comment by wking** [comment]
And if we go with one LGTM, you'll also want to update [the maintainer's guide][1].

[1]: https://github.com/opencontainers/runtime-tools/blame/e2410351bee2ebbc17d7ded4f07ce0af1444ff3a/MAINTAINERS_GUIDE.md#L66-L67

**Comment by liangchenye** [comment]
@caniszczyk Hi, can you update the 'MAINTAINERS_GUIDE.md' ?

**Comment by liangchenye** [comment]
LGTM
I think we can merge it first, I'll update the maintainer's guide later.

**Comment by q384566678** [comment]
LGTM

**Comment by wking** [comment]
> Should this also come with a `MAINTAINERS` prune?

I haven't noticed difficulty collecting two LGTMs, but there are certainly a few nominal maintainers that LGTM pulls very rarely.  On the other hand, free-riding non-spec maintainers aren't much of a functional issue.

**Comment by liangchenye** [comment]
I think the change is about: the strategy of the tool project could be 'more agile and mistake tolerable' .

**Pull request merged**
