### PR TITLE
Switch to GHA CI

### PR DESCRIPTION
**Pull request by kolyshkin**
~~_This PR builds on and currently includes PR #727, thus the draft status._~~

This removes Travis CI config and adds GHA CI. You can see how it looks like at https://github.com/kolyshkin/runtime-tools/actions/runs/1361288633 and https://github.com/kolyshkin/runtime-tools/pull/1

Also:
 - fix many linter warnings from the default golangci-lint config
    (alas not all of them from errcheck -- there are way too many 😿, I gave up)
 - add golangci-lint, fix all its warnings
 - re-add commit subject length validation

Addresses: #726

### CODE REVIEW

**Comment by kolyshkin** [comment]
> This all looks sane to me -- do you think it would be useful for me to try pushing your branch to a new branch here on the origin so the PR can actually run the actions?

As noted in description, I have those ran at https://github.com/kolyshkin/runtime-tools/actions/runs/1344345504, don't think it makes any difference which repo it is.

This is still WIP; currently working on enabling golangci-lint and it's overwhelming :( Guess I'll have to disable errcheck linter :(

I'll let you know once it's ready @tianon, thanks for looking!

**Comment by tianon** [comment]
Thanks to Travis it's going to require a repository administrator (which excludes me 😅).

@vbatts is that you? @caniszczyk?

IMO both PRs look great and merging this which contains both seems like a simpler path, but I don't have any issue with any solution that unblocks Kir and gets this repo able to progress again. 😁

**Comment by caniszczyk** [comment]
I truly don't know how to disable the Travis CI check

**Comment by kolyshkin** [comment]
@caniszczyk this is not about disabling Travis, this is about removing travis (and, maybe, pullapprove, too) from the list of jobs required to merge a PR. This is under Settings -> Branches -> Branch protection rules -> master -> edit -> Status checks that are required. Need to remove travis-ci from that list (and later add GHA CI jobs added by this PR).

**Pull request merged**
