### PR TITLE
Add Go Report Card

### PR DESCRIPTION
**Pull request by caniszczyk**
https://goreportcard.com/report/github.com/opencontainers/runtime-tools

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
I don't know what's going on with the Travis failure; it seems like
$TRAVIS_COMMIT_RANGE is unset [1].  Travis has had problems with that
in the past (travis-ci/travis-ci#1719), but they claim to have fixed
them.  Maybe we just need to kick the tests?

c71bd20c looks good to me.

[1]: https://travis-ci.org/opencontainers/runtime-tools/builds/167782152#L176

**Comment by Mashimiao** [comment]
@caniszczyk   Do you really want to create a new branch of this project?
I think you should create branch on you own fork and create PR with that branch, not like this.

**Comment by liangchenye** [comment]
@Mashimiao I guess you miss read the branch.

**Comment by Mashimiao** [comment]
No, I think I didn't.   A new branch `add-go-report-card` has been created and pushed to this project.

**Comment by liangchenye** [comment]
Oh yes, @Mashimiao I though that is @caniszczyk 's own branch.

**Comment by liangchenye** [comment]
Oh yes, @Mashimiao I did not notice this :)

**Pull request closed without merging**
